events {}

http {
  resolver 127.0.0.11 valid=5s ipv6=off;

  upstream gateway_pool {
    zone gateway_pool 64k;
    server gateway:8080 resolve;
  }

  server {
    listen 8080;

    location / {
      proxy_pass http://gateway_pool;
      proxy_http_version 1.1;
      proxy_buffering off;
      proxy_read_timeout 60s;
      proxy_set_header Host $host;
      proxy_set_header X-Request-Id $request_id;
    }
  }
}
